---
puppet::host : 'puppet'
puppet::port : 8140

gitlab::host : 'repositories'
gitlab::port : 80

jenkins::host : 'karajan'
jenkins::port : 8080

mesos::host        : 'karajan'
mesos::port        : 5050
mesos::master_port : "%{hiera('mesos::port')}"
mesos::log_dir     : '/var/log/mesos'
mesos::conf_dir    : '/etc/mesos'
mesos::owner       : 'mesos'
mesos::group       : 'mesos'

rundeck::host  : 'karajan'
rundeck::port  : 4440
rundeck::user  : 'rundeck'
rundeck::group : 'rundeck'
rundeck::server_web_context: "/rundeck"
rundeck::grails_server_url : "http://%{hiera('rundeck::host')}.%{::domain}:%{hiera('rundeck::port')}%{hiera('rundeck::server_web_context')}"

pass:
  - path: /puppet
    url: "http://%{hiera('puppet::host')}.%{::domain}:%{hiera('puppet::port')}"
  - path: /rundeck
    url: "%{hiera('rundeck::grails_server_url')}"
  - path: /gitlab
    url: "http://%{hiera('gitlab::host')}.%{::domain}:%{hiera('gitlab::port')}/gitlab"
  - path: /jenkins
    url: "http://%{hiera('jenkins::host')}.%{::domain}:%{hiera('jenkins::port')}/jenkins"
  - path: /mesos
    url: "http://%{hiera('mesos::host')}.%{::domain}:%{hiera('mesos::port')}/"
