---
applications:
  - name   : 'petclinic'
    git_url: 'https://github.com/oloc/g10b-petclinic.git'

docker_registry::host: "%{hiera('g10b-repositories')}.%{::domain}"
#docker_registry::host: 'hub.docker.com'
docker_registry::port: 5000

elasticsearch::host  : "%{hiera('g10b-metrology')}"
elasticsearch::port  : 9200
elasticsearch::user  : 'elasticsearch'
elasticsearch::group : 'elasticsearch'

elasticsearch::plugins:
  mobz/elasticsearch-head:
    module_dir: 'head'
  lukas-vlcek/bigdesk:
    module_dir: 'bigdesk'
  elasticsearch/marvel:
    module_dir: 'marvel'

gitlab::host : "%{hiera('g10b-repositories')}"
gitlab::port : 80

jenkins::host : "%{hiera('g10b-orchestration')}"
jenkins::port : 8080

jenkins::plugins:
  ssh-credentials:
    version: 'latest'
  scm-api:
    version: 'latest'
  mailer:
    version: 'latest'
  git:
    version: 'latest'
  jquery:
    version: 'latest'
  parameterized-trigger:
    version: 'latest'
  build-pipeline-plugin:
    version: 'latest'
  docker-commons:
    version: 'latest'
  docker-build-step:
    version: 'latest'
  throttle-concurrents:
    version: 'latest'

kibana::host  : "%{hiera('g10b-metrology')}"
kibana::port  : 5601
kibana::user  : 'kibana'
kibana::group : 'kibana'

logstash::host : "%{hiera('g10b-metrology')}"
logstash::port : 5000

mesos::host : "%{hiera('g10b-orchestration')}"
mesos::port : 5050
mesos::owner : 'mesos'
mesos::group : 'mesos'

puppet::host : "%{hiera('g10b-puppet-master')}"
puppet::port : 8140

rundeck::host              : "%{hiera('g10b-orchestration')}"
rundeck::port              : 4440
rundeck::user              : 'rundeck'
rundeck::group             : 'rundeck'
rundeck::server_web_context: "/rundeck"
rundeck::grails_server_url : "http://%{hiera('rundeck::host')}.%{::domain}:%{hiera('rundeck::port')}%{hiera('rundeck::server_web_context')}"
